// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD0H6idodYzGTmp9k8t4yXLM2JWYoYtrU',
    appId: '1:883252520949:web:60ef273c60ce273739a2bc',
    messagingSenderId: '883252520949',
    projectId: 'mova-f33ea',
    authDomain: 'mova-f33ea.firebaseapp.com',
    storageBucket: 'mova-f33ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKxjR5tXJyNZl4N9JT_WFdAjS5dKrWVkk',
    appId: '1:883252520949:android:955186fabae1b19039a2bc',
    messagingSenderId: '883252520949',
    projectId: 'mova-f33ea',
    storageBucket: 'mova-f33ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcU2USf0lr99hDJbGWaF2D53AXJwnlQ8U',
    appId: '1:883252520949:ios:4fe9383dbf6018dd39a2bc',
    messagingSenderId: '883252520949',
    projectId: 'mova-f33ea',
    storageBucket: 'mova-f33ea.appspot.com',
    iosClientId: '883252520949-2pt9g895dsg54hei474udvo8p4qk218j.apps.googleusercontent.com',
    iosBundleId: 'com.example.mova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcU2USf0lr99hDJbGWaF2D53AXJwnlQ8U',
    appId: '1:883252520949:ios:4fe9383dbf6018dd39a2bc',
    messagingSenderId: '883252520949',
    projectId: 'mova-f33ea',
    storageBucket: 'mova-f33ea.appspot.com',
    iosClientId: '883252520949-2pt9g895dsg54hei474udvo8p4qk218j.apps.googleusercontent.com',
    iosBundleId: 'com.example.mova',
  );
}
